targets:
  $default:
    builders:
      generators:
        enabled: true
        # options:
        #   build_extensions:
        #     '^lib/models/{{}}.dart': 'lib/models/generated/{{}}.foo.dart'

builders:
  generators:
    target: ":generators"
    import: "package:generators/builder.dart"
    builder_factories: ["extGen", "myGen"]
    build_extensions: { ".dart": [".gen.g.dart"] }
    # build_extensions: { ".dart": [".my_generator.dart"] }
    auto_apply: dependents
    build_to: cache
    # build_to: source
    applies_builders: ["source_gen:combining_builder"]
