name: generators
description: Custom dart file generators
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build:
  source_gen:

dev_dependencies:
  build_test:
  build_runner:
  test: ^1.0.0
